<?php

namespace Database\Seeders;

use App\Models\Furniture;
use Illuminate\Database\Seeder;

class FurnitureSeeder extends Seeder
{
    public function run(): void
    {
        $furniture = [
            // ==================== SEATING ====================
            [
                'name' => 'Modern L-Shape Sofa',
                'description' => 'Spacious L-shaped sectional sofa with premium fabric upholstery. Features high-density foam cushions for maximum comfort. Perfect for large living rooms.',
                'category' => 'Seating',
                'room' => 'Living Room',
                'price' => 125000,
                'dimensions' => ['width' => 280, 'height' => 85, 'depth' => 180],
                'material' => 'Fabric & Wood',
                'color' => 'Gray',
                'stock' => 15,
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 1,
            ],
            [
                'name' => 'Classic 3-Seater Sofa',
                'description' => 'Elegant 3-seater sofa with tufted backrest and rolled arms. Solid wood frame with premium velvet upholstery.',
                'category' => 'Seating',
                'room' => 'Living Room',
                'price' => 85000,
                'dimensions' => ['width' => 220, 'height' => 90, 'depth' => 95],
                'material' => 'Velvet & Teak',
                'color' => 'Navy Blue',
                'stock' => 20,
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 2,
            ],
            [
                'name' => 'Recliner Sofa Set',
                'description' => 'Luxurious recliner sofa with motorized reclining mechanism. Premium leather upholstery with USB charging ports.',
                'category' => 'Seating',
                'room' => 'Living Room',
                'price' => 175000,
                'dimensions' => ['width' => 240, 'height' => 100, 'depth' => 95],
                'material' => 'Genuine Leather',
                'color' => 'Brown',
                'stock' => 8,
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 3,
            ],
            [
                'name' => 'Wingback Armchair',
                'description' => 'Classic wingback armchair with button-tufted back. Ideal for reading corners and accent seating.',
                'category' => 'Seating',
                'room' => 'Living Room',
                'price' => 35000,
                'dimensions' => ['width' => 80, 'height' => 110, 'depth' => 85],
                'material' => 'Fabric & Wood',
                'color' => 'Emerald Green',
                'stock' => 25,
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 4,
            ],
            [
                'name' => 'Accent Chair with Ottoman',
                'description' => 'Modern accent chair with matching ottoman. Perfect for creating a cozy reading nook.',
                'category' => 'Seating',
                'room' => 'Living Room',
                'price' => 28000,
                'dimensions' => ['width' => 75, 'height' => 95, 'depth' => 80],
                'material' => 'Linen & Metal',
                'color' => 'Beige',
                'stock' => 30,
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 5,
            ],
            [
                'name' => 'Ergonomic Office Chair',
                'description' => 'High-back ergonomic office chair with lumbar support, adjustable armrests, and breathable mesh back.',
                'category' => 'Seating',
                'room' => 'Office',
                'price' => 22000,
                'dimensions' => ['width' => 65, 'height' => 120, 'depth' => 65],
                'material' => 'Mesh & Metal',
                'color' => 'Black',
                'stock' => 50,
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 6,
            ],
            [
                'name' => 'Executive Leather Chair',
                'description' => 'Premium executive chair with genuine leather upholstery. Features tilt mechanism and chrome base.',
                'category' => 'Seating',
                'room' => 'Office',
                'price' => 45000,
                'dimensions' => ['width' => 70, 'height' => 125, 'depth' => 70],
                'material' => 'Leather & Chrome',
                'color' => 'Black',
                'stock' => 20,
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 7,
            ],
            [
                'name' => 'Dining Chair Set (6 pcs)',
                'description' => 'Set of 6 elegant dining chairs with padded seats and solid wood frames. Modern Scandinavian design.',
                'category' => 'Seating',
                'room' => 'Dining Room',
                'price' => 48000,
                'dimensions' => ['width' => 45, 'height' => 90, 'depth' => 50],
                'material' => 'Oak Wood & Fabric',
                'color' => 'Natural Oak',
                'stock' => 15,
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 8,
            ],
            [
                'name' => 'Bar Stool Set (4 pcs)',
                'description' => 'Modern bar stools with footrest and swivel base. Counter height design with padded seats.',
                'category' => 'Seating',
                'room' => 'Kitchen',
                'price' => 24000,
                'dimensions' => ['width' => 40, 'height' => 75, 'depth' => 40],
                'material' => 'Metal & Faux Leather',
                'color' => 'Black',
                'stock' => 20,
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 9,
            ],
            [
                'name' => 'Bench with Storage',
                'description' => 'Upholstered bench with hidden storage compartment. Perfect for entryway or bedroom.',
                'category' => 'Seating',
                'room' => 'Bedroom',
                'price' => 18000,
                'dimensions' => ['width' => 120, 'height' => 50, 'depth' => 45],
                'material' => 'Fabric & MDF',
                'color' => 'Gray',
                'stock' => 25,
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 10,
            ],

            // ==================== TABLES ====================
            [
                'name' => 'Glass Top Coffee Table',
                'description' => 'Contemporary coffee table with tempered glass top and brushed metal frame. Lower shelf for storage.',
                'category' => 'Tables',
                'room' => 'Living Room',
                'price' => 28000,
                'dimensions' => ['width' => 120, 'height' => 45, 'depth' => 60],
                'material' => 'Glass & Metal',
                'color' => 'Silver',
                'stock' => 30,
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 11,
            ],
            [
                'name' => 'Wooden Center Table',
                'description' => 'Solid sheesham wood center table with natural finish. Traditional carved design.',
                'category' => 'Tables',
                'room' => 'Living Room',
                'price' => 35000,
                'dimensions' => ['width' => 110, 'height' => 40, 'depth' => 55],
                'material' => 'Sheesham Wood',
                'color' => 'Walnut',
                'stock' => 20,
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 12,
            ],
            [
                'name' => 'Nesting Tables Set (3 pcs)',
                'description' => 'Set of 3 nesting tables in varying sizes. Space-saving design with marble-look top.',
                'category' => 'Tables',
                'room' => 'Living Room',
                'price' => 22000,
                'dimensions' => ['width' => 50, 'height' => 55, 'depth' => 50],
                'material' => 'MDF & Metal',
                'color' => 'White Marble',
                'stock' => 25,
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 13,
            ],
            [
                'name' => '6-Seater Dining Table',
                'description' => 'Solid wood dining table with elegant tapered legs. Seats 6 comfortably. Scratch-resistant finish.',
                'category' => 'Tables',
                'room' => 'Dining Room',
                'price' => 55000,
                'dimensions' => ['width' => 180, 'height' => 75, 'depth' => 90],
                'material' => 'Teak Wood',
                'color' => 'Dark Brown',
                'stock' => 12,
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 14,
            ],
            [
                'name' => '8-Seater Extendable Dining Table',
                'description' => 'Extendable dining table that seats 6-8 people. Butterfly leaf mechanism for easy extension.',
                'category' => 'Tables',
                'room' => 'Dining Room',
                'price' => 75000,
                'dimensions' => ['width' => 200, 'height' => 76, 'depth' => 100],
                'material' => 'Oak Wood',
                'color' => 'Natural',
                'stock' => 8,
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 15,
            ],
            [
                'name' => 'Round Dining Table',
                'description' => 'Modern round dining table with pedestal base. Perfect for 4 people. Easy to clean surface.',
                'category' => 'Tables',
                'room' => 'Dining Room',
                'price' => 42000,
                'dimensions' => ['width' => 120, 'height' => 75, 'depth' => 120],
                'material' => 'MDF & Metal',
                'color' => 'White',
                'stock' => 15,
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 16,
            ],
            [
                'name' => 'Executive Office Desk',
                'description' => 'L-shaped executive desk with built-in cable management. Spacious work surface with drawer unit.',
                'category' => 'Tables',
                'room' => 'Office',
                'price' => 48000,
                'dimensions' => ['width' => 180, 'height' => 75, 'depth' => 80],
                'material' => 'Engineered Wood',
                'color' => 'Walnut',
                'stock' => 18,
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 17,
            ],
            [
                'name' => 'Computer Study Table',
                'description' => 'Compact study table with keyboard tray and CPU stand. Ideal for home office setup.',
                'category' => 'Tables',
                'room' => 'Office',
                'price' => 15000,
                'dimensions' => ['width' => 100, 'height' => 75, 'depth' => 60],
                'material' => 'Particle Board',
                'color' => 'Oak',
                'stock' => 40,
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 18,
            ],
            [
                'name' => 'Standing Desk',
                'description' => 'Electric height-adjustable standing desk. Memory presets for sitting and standing positions.',
                'category' => 'Tables',
                'room' => 'Office',
                'price' => 38000,
                'dimensions' => ['width' => 140, 'height' => 120, 'depth' => 70],
                'material' => 'Bamboo & Steel',
                'color' => 'Natural Bamboo',
                'stock' => 15,
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 19,
            ],
            [
                'name' => 'Bedside Table Set (2 pcs)',
                'description' => 'Matching pair of bedside tables with drawer and open shelf. Modern minimalist design.',
                'category' => 'Tables',
                'room' => 'Bedroom',
                'price' => 16000,
                'dimensions' => ['width' => 45, 'height' => 55, 'depth' => 40],
                'material' => 'MDF',
                'color' => 'White',
                'stock' => 35,
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 20,
            ],
            [
                'name' => 'Console Table',
                'description' => 'Elegant console table with marble top and gold metal frame. Perfect for entryways.',
                'category' => 'Tables',
                'room' => 'Living Room',
                'price' => 32000,
                'dimensions' => ['width' => 120, 'height' => 80, 'depth' => 35],
                'material' => 'Marble & Metal',
                'color' => 'Gold',
                'stock' => 12,
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 21,
            ],

            // ==================== BEDS ====================
            [
                'name' => 'King Size Platform Bed',
                'description' => 'Modern platform bed with upholstered headboard. Solid wood slat support. No box spring needed.',
                'category' => 'Beds',
                'room' => 'Bedroom',
                'price' => 85000,
                'dimensions' => ['width' => 200, 'height' => 120, 'depth' => 210],
                'material' => 'Fabric & Wood',
                'color' => 'Gray',
                'stock' => 10,
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 22,
            ],
            [
                'name' => 'Queen Size Storage Bed',
                'description' => 'Queen bed with hydraulic lift-up storage. Maximizes bedroom space. Cushioned headboard.',
                'category' => 'Beds',
                'room' => 'Bedroom',
                'price' => 72000,
                'dimensions' => ['width' => 160, 'height' => 110, 'depth' => 200],
                'material' => 'Engineered Wood',
                'color' => 'Wenge',
                'stock' => 12,
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 23,
            ],
            [
                'name' => 'Traditional Carved Wooden Bed',
                'description' => 'Handcrafted solid wood bed with intricate carvings. Heritage design with modern comfort.',
                'category' => 'Beds',
                'room' => 'Bedroom',
                'price' => 125000,
                'dimensions' => ['width' => 180, 'height' => 150, 'depth' => 210],
                'material' => 'Rosewood',
                'color' => 'Dark Brown',
                'stock' => 5,
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 24,
            ],
            [
                'name' => 'Single Bed with Trundle',
                'description' => 'Space-saving single bed with pull-out trundle. Perfect for kids rooms or guest bedrooms.',
                'category' => 'Beds',
                'room' => 'Bedroom',
                'price' => 35000,
                'dimensions' => ['width' => 100, 'height' => 90, 'depth' => 200],
                'material' => 'Pine Wood',
                'color' => 'White',
                'stock' => 20,
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 25,
            ],
            [
                'name' => 'Bunk Bed with Study Table',
                'description' => 'Kids bunk bed with integrated study table and storage. Safety rails included.',
                'category' => 'Beds',
                'room' => 'Bedroom',
                'price' => 58000,
                'dimensions' => ['width' => 100, 'height' => 180, 'depth' => 200],
                'material' => 'Metal & MDF',
                'color' => 'Blue & White',
                'stock' => 15,
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 26,
            ],
            [
                'name' => 'Canopy Bed Frame',
                'description' => 'Elegant four-poster canopy bed frame. Metal construction with decorative finials.',
                'category' => 'Beds',
                'room' => 'Bedroom',
                'price' => 95000,
                'dimensions' => ['width' => 180, 'height' => 220, 'depth' => 210],
                'material' => 'Wrought Iron',
                'color' => 'Antique Gold',
                'stock' => 6,
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 27,
            ],
            [
                'name' => 'Sofa Cum Bed',
                'description' => 'Convertible sofa bed with easy fold-out mechanism. Perfect for guest rooms and small spaces.',
                'category' => 'Beds',
                'room' => 'Living Room',
                'price' => 45000,
                'dimensions' => ['width' => 180, 'height' => 85, 'depth' => 90],
                'material' => 'Fabric & Metal',
                'color' => 'Navy Blue',
                'stock' => 18,
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 28,
            ],
            [
                'name' => 'Daybed with Cushions',
                'description' => 'Versatile daybed for lounging and sleeping. Comes with matching back cushions.',
                'category' => 'Beds',
                'room' => 'Living Room',
                'price' => 52000,
                'dimensions' => ['width' => 200, 'height' => 80, 'depth' => 100],
                'material' => 'Rattan & Fabric',
                'color' => 'Natural',
                'stock' => 10,
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 29,
            ],

            // ==================== STORAGE ====================
            [
                'name' => '4-Door Wardrobe',
                'description' => 'Spacious 4-door wardrobe with mirror. Features hanging space, shelves, and drawers.',
                'category' => 'Storage',
                'room' => 'Bedroom',
                'price' => 75000,
                'dimensions' => ['width' => 200, 'height' => 210, 'depth' => 60],
                'material' => 'Engineered Wood',
                'color' => 'White',
                'stock' => 10,
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 30,
            ],
            [
                'name' => 'Sliding Door Wardrobe',
                'description' => 'Modern sliding door wardrobe with full-length mirror. Space-saving design.',
                'category' => 'Storage',
                'room' => 'Bedroom',
                'price' => 85000,
                'dimensions' => ['width' => 180, 'height' => 220, 'depth' => 65],
                'material' => 'MDF & Glass',
                'color' => 'Gray Oak',
                'stock' => 8,
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 31,
            ],
            [
                'name' => 'Walk-in Closet System',
                'description' => 'Modular walk-in closet system with customizable shelves, drawers, and hanging rods.',
                'category' => 'Storage',
                'room' => 'Bedroom',
                'price' => 150000,
                'dimensions' => ['width' => 300, 'height' => 240, 'depth' => 60],
                'material' => 'Laminated Wood',
                'color' => 'Cream',
                'stock' => 5,
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 32,
            ],
            [
                'name' => 'TV Unit with Storage',
                'description' => 'Modern TV unit with cabinets and open shelves. Cable management system included.',
                'category' => 'Storage',
                'room' => 'Living Room',
                'price' => 35000,
                'dimensions' => ['width' => 180, 'height' => 45, 'depth' => 40],
                'material' => 'MDF',
                'color' => 'Walnut',
                'stock' => 25,
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 33,
            ],
            [
                'name' => 'Wall-Mounted Entertainment Unit',
                'description' => 'Floating entertainment unit with LED backlight. Sleek modern design.',
                'category' => 'Storage',
                'room' => 'Living Room',
                'price' => 48000,
                'dimensions' => ['width' => 240, 'height' => 35, 'depth' => 35],
                'material' => 'High Gloss MDF',
                'color' => 'Black',
                'stock' => 15,
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 34,
            ],
            [
                'name' => 'Bookshelf 5-Tier',
                'description' => 'Open bookshelf with 5 tiers. Industrial style with metal frame and wooden shelves.',
                'category' => 'Storage',
                'room' => 'Living Room',
                'price' => 22000,
                'dimensions' => ['width' => 80, 'height' => 180, 'depth' => 35],
                'material' => 'Wood & Metal',
                'color' => 'Rustic Brown',
                'stock' => 30,
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 35,
            ],
            [
                'name' => 'Display Cabinet with Glass Doors',
                'description' => 'Elegant display cabinet with tempered glass doors. LED lighting inside.',
                'category' => 'Storage',
                'room' => 'Living Room',
                'price' => 55000,
                'dimensions' => ['width' => 120, 'height' => 180, 'depth' => 40],
                'material' => 'Solid Wood & Glass',
                'color' => 'Dark Wood',
                'stock' => 10,
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 36,
            ],
            [
                'name' => 'Kitchen Cabinet Set',
                'description' => 'Complete modular kitchen cabinet set. Includes base, wall, and tall units.',
                'category' => 'Storage',
                'room' => 'Kitchen',
                'price' => 185000,
                'dimensions' => ['width' => 300, 'height' => 210, 'depth' => 60],
                'material' => 'Marine Plywood',
                'color' => 'White & Wood',
                'stock' => 5,
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 37,
            ],
            [
                'name' => 'Shoe Rack 3-Tier',
                'description' => 'Compact shoe rack with 3 tiers. Holds up to 15 pairs of shoes.',
                'category' => 'Storage',
                'room' => 'Living Room',
                'price' => 8000,
                'dimensions' => ['width' => 80, 'height' => 85, 'depth' => 30],
                'material' => 'MDF',
                'color' => 'Oak',
                'stock' => 50,
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 38,
            ],
            [
                'name' => 'Chest of Drawers',
                'description' => '6-drawer chest with soft-close mechanism. Classic design with metal handles.',
                'category' => 'Storage',
                'room' => 'Bedroom',
                'price' => 32000,
                'dimensions' => ['width' => 100, 'height' => 120, 'depth' => 45],
                'material' => 'Solid Wood',
                'color' => 'White',
                'stock' => 20,
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 39,
            ],
            [
                'name' => 'Filing Cabinet 3-Drawer',
                'description' => 'Metal filing cabinet with lock. Legal and letter size compatible.',
                'category' => 'Storage',
                'room' => 'Office',
                'price' => 12000,
                'dimensions' => ['width' => 40, 'height' => 100, 'depth' => 50],
                'material' => 'Steel',
                'color' => 'Black',
                'stock' => 35,
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 40,
            ],

            // ==================== LIGHTING ====================
            [
                'name' => 'Crystal Chandelier',
                'description' => 'Stunning crystal chandelier with 12 lights. Creates elegant ambiance for dining rooms.',
                'category' => 'Lighting',
                'room' => 'Dining Room',
                'price' => 85000,
                'dimensions' => ['width' => 80, 'height' => 90, 'depth' => 80],
                'material' => 'Crystal & Metal',
                'color' => 'Gold',
                'stock' => 8,
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 41,
            ],
            [
                'name' => 'Modern Pendant Light',
                'description' => 'Minimalist pendant light with frosted glass shade. Adjustable hanging height.',
                'category' => 'Lighting',
                'room' => 'Dining Room',
                'price' => 12000,
                'dimensions' => ['width' => 30, 'height' => 40, 'depth' => 30],
                'material' => 'Glass & Metal',
                'color' => 'Black',
                'stock' => 40,
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 42,
            ],
            [
                'name' => 'LED Ceiling Light Panel',
                'description' => 'Ultra-slim LED panel light with dimming function. Energy efficient 36W.',
                'category' => 'Lighting',
                'room' => 'Living Room',
                'price' => 5500,
                'dimensions' => ['width' => 60, 'height' => 5, 'depth' => 60],
                'material' => 'Aluminum & Acrylic',
                'color' => 'White',
                'stock' => 100,
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 43,
            ],
            [
                'name' => 'Floor Lamp Arc Design',
                'description' => 'Elegant arc floor lamp with marble base. Adjustable shade direction.',
                'category' => 'Lighting',
                'room' => 'Living Room',
                'price' => 18000,
                'dimensions' => ['width' => 40, 'height' => 180, 'depth' => 100],
                'material' => 'Metal & Marble',
                'color' => 'Brass',
                'stock' => 20,
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 44,
            ],
            [
                'name' => 'Tripod Floor Lamp',
                'description' => 'Wooden tripod floor lamp with fabric drum shade. Scandinavian style.',
                'category' => 'Lighting',
                'room' => 'Living Room',
                'price' => 14000,
                'dimensions' => ['width' => 50, 'height' => 150, 'depth' => 50],
                'material' => 'Wood & Fabric',
                'color' => 'Natural',
                'stock' => 25,
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 45,
            ],
            [
                'name' => 'Table Lamp Ceramic',
                'description' => 'Handcrafted ceramic table lamp with linen shade. Unique textured finish.',
                'category' => 'Lighting',
                'room' => 'Bedroom',
                'price' => 6500,
                'dimensions' => ['width' => 25, 'height' => 50, 'depth' => 25],
                'material' => 'Ceramic & Linen',
                'color' => 'Blue',
                'stock' => 35,
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 46,
            ],
            [
                'name' => 'Desk Lamp LED',
                'description' => 'Adjustable LED desk lamp with touch controls. USB charging port. Eye-care technology.',
                'category' => 'Lighting',
                'room' => 'Office',
                'price' => 3500,
                'dimensions' => ['width' => 20, 'height' => 45, 'depth' => 20],
                'material' => 'Aluminum & Plastic',
                'color' => 'Silver',
                'stock' => 60,
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 47,
            ],
            [
                'name' => 'Wall Sconce Set (2 pcs)',
                'description' => 'Pair of modern wall sconces with up/down lighting. Creates ambient wall washing effect.',
                'category' => 'Lighting',
                'room' => 'Living Room',
                'price' => 8500,
                'dimensions' => ['width' => 12, 'height' => 25, 'depth' => 10],
                'material' => 'Metal',
                'color' => 'Matte Black',
                'stock' => 40,
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 48,
            ],
            [
                'name' => 'Bathroom Vanity Light',
                'description' => '4-light vanity fixture for bathroom mirrors. IP44 rated for moisture resistance.',
                'category' => 'Lighting',
                'room' => 'Bathroom',
                'price' => 7500,
                'dimensions' => ['width' => 60, 'height' => 15, 'depth' => 15],
                'material' => 'Chrome & Glass',
                'color' => 'Chrome',
                'stock' => 30,
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 49,
            ],
            [
                'name' => 'String Lights Decorative',
                'description' => 'Warm white LED string lights 10m. Perfect for bedroom or patio decoration.',
                'category' => 'Lighting',
                'room' => 'Bedroom',
                'price' => 1500,
                'dimensions' => ['width' => 0, 'height' => 0, 'depth' => 0],
                'material' => 'Copper & LED',
                'color' => 'Warm White',
                'stock' => 100,
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 50,
            ],

            // ==================== DECOR ====================
            [
                'name' => 'Large Wall Mirror',
                'description' => 'Full-length wall mirror with ornate gold frame. Adds depth and light to any room.',
                'category' => 'Decor',
                'room' => 'Living Room',
                'price' => 28000,
                'dimensions' => ['width' => 80, 'height' => 180, 'depth' => 5],
                'material' => 'Glass & Wood',
                'color' => 'Gold',
                'stock' => 15,
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 51,
            ],
            [
                'name' => 'Round Decorative Mirror',
                'description' => 'Contemporary round mirror with sunburst frame. Statement piece for walls.',
                'category' => 'Decor',
                'room' => 'Living Room',
                'price' => 15000,
                'dimensions' => ['width' => 90, 'height' => 90, 'depth' => 3],
                'material' => 'Metal & Glass',
                'color' => 'Black',
                'stock' => 25,
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 52,
            ],
            [
                'name' => 'Artificial Plant Large',
                'description' => 'Realistic artificial Fiddle Leaf Fig tree in decorative pot. Low maintenance greenery.',
                'category' => 'Decor',
                'room' => 'Living Room',
                'price' => 8500,
                'dimensions' => ['width' => 50, 'height' => 150, 'depth' => 50],
                'material' => 'Plastic & Fabric',
                'color' => 'Green',
                'stock' => 30,
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 53,
            ],
            [
                'name' => 'Decorative Vase Set (3 pcs)',
                'description' => 'Set of 3 ceramic vases in varying heights. Modern minimalist design.',
                'category' => 'Decor',
                'room' => 'Living Room',
                'price' => 5500,
                'dimensions' => ['width' => 15, 'height' => 35, 'depth' => 15],
                'material' => 'Ceramic',
                'color' => 'White',
                'stock' => 40,
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 54,
            ],
            [
                'name' => 'Wall Clock Large',
                'description' => 'Oversized wall clock with Roman numerals. Silent quartz movement.',
                'category' => 'Decor',
                'room' => 'Living Room',
                'price' => 4500,
                'dimensions' => ['width' => 60, 'height' => 60, 'depth' => 5],
                'material' => 'Wood & Metal',
                'color' => 'Antique',
                'stock' => 35,
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 55,
            ],
            [
                'name' => 'Framed Art Print Set (3 pcs)',
                'description' => 'Set of 3 abstract art prints in black frames. Gallery-quality printing.',
                'category' => 'Decor',
                'room' => 'Living Room',
                'price' => 12000,
                'dimensions' => ['width' => 40, 'height' => 50, 'depth' => 3],
                'material' => 'Paper & Wood',
                'color' => 'Multi',
                'stock' => 25,
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 56,
            ],
            [
                'name' => 'Area Rug Persian Style',
                'description' => 'Machine-woven area rug with traditional Persian pattern. Soft pile, easy to clean.',
                'category' => 'Decor',
                'room' => 'Living Room',
                'price' => 25000,
                'dimensions' => ['width' => 200, 'height' => 1, 'depth' => 300],
                'material' => 'Polypropylene',
                'color' => 'Red & Navy',
                'stock' => 15,
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 57,
            ],
            [
                'name' => 'Shag Rug Modern',
                'description' => 'Ultra-soft shag rug for bedroom or living room. Non-slip backing.',
                'category' => 'Decor',
                'room' => 'Bedroom',
                'price' => 18000,
                'dimensions' => ['width' => 160, 'height' => 2, 'depth' => 230],
                'material' => 'Polyester',
                'color' => 'Gray',
                'stock' => 20,
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 58,
            ],
            [
                'name' => 'Throw Pillow Set (4 pcs)',
                'description' => 'Set of 4 decorative throw pillows with removable covers. Various patterns.',
                'category' => 'Decor',
                'room' => 'Living Room',
                'price' => 4000,
                'dimensions' => ['width' => 45, 'height' => 45, 'depth' => 15],
                'material' => 'Cotton & Polyester',
                'color' => 'Mixed',
                'stock' => 50,
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 59,
            ],
            [
                'name' => 'Curtain Panel Pair',
                'description' => 'Blackout curtains with grommet top. Thermal insulated, blocks 99% light.',
                'category' => 'Decor',
                'room' => 'Bedroom',
                'price' => 6500,
                'dimensions' => ['width' => 140, 'height' => 270, 'depth' => 0],
                'material' => 'Polyester Blend',
                'color' => 'Navy',
                'stock' => 40,
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 60,
            ],
        ];

        foreach ($furniture as $item) {
            Furniture::create($item);
        }
    }
}
