<?php

namespace Database\Seeders;

use App\Models\Material;
use Illuminate\Database\Seeder;

class MaterialSeeder extends Seeder
{
    public function run(): void
    {
        $materials = [
            // ==================== CONSTRUCTION - STRUCTURAL ====================
            [
                'name' => 'M20 Grade Concrete',
                'description' => 'Standard concrete mix for foundations, columns, and beams. Compressive strength: 20 MPa at 28 days. Cement:Sand:Aggregate ratio 1:1.5:3.',
                'category' => 'Construction',
                'type' => 'Structural',
                'price_per_unit' => 8500,
                'unit' => 'cu.m',
                'color' => '#8B8B83',
                'brand' => 'Ready Mix',
                'specifications' => 'Slump: 75-100mm, Max aggregate size: 20mm',
                'availability' => 'Available',
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 1,
            ],
            [
                'name' => 'M25 Grade Concrete',
                'description' => 'High strength concrete for structural elements. Compressive strength: 25 MPa. Ideal for RCC work.',
                'category' => 'Construction',
                'type' => 'Structural',
                'price_per_unit' => 9200,
                'unit' => 'cu.m',
                'color' => '#7A7A72',
                'brand' => 'Ready Mix',
                'specifications' => 'Slump: 75-100mm, Water-cement ratio: 0.44',
                'availability' => 'Available',
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 2,
            ],
            [
                'name' => 'M30 Grade Concrete',
                'description' => 'Premium grade concrete for high-rise buildings and heavy load structures. Compressive strength: 30 MPa.',
                'category' => 'Construction',
                'type' => 'Structural',
                'price_per_unit' => 10500,
                'unit' => 'cu.m',
                'color' => '#696963',
                'brand' => 'Ready Mix',
                'specifications' => 'High performance mix with admixtures',
                'availability' => 'Available',
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 3,
            ],
            [
                'name' => 'TMT Steel Bars Fe500D',
                'description' => 'Thermo-mechanically treated reinforcement bars. High tensile strength with superior bendability. Earthquake resistant.',
                'category' => 'Construction',
                'type' => 'Structural',
                'price_per_unit' => 105,
                'unit' => 'kg',
                'color' => '#4A4A4A',
                'brand' => 'Himal Steel',
                'specifications' => 'Sizes: 8mm, 10mm, 12mm, 16mm, 20mm, 25mm',
                'availability' => 'Available',
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 4,
            ],
            [
                'name' => 'TMT Steel Bars Fe550',
                'description' => 'Premium grade TMT bars for heavy construction. Higher yield strength for structural efficiency.',
                'category' => 'Construction',
                'type' => 'Structural',
                'price_per_unit' => 115,
                'unit' => 'kg',
                'color' => '#3D3D3D',
                'brand' => 'Jagdamba Steel',
                'specifications' => 'Yield strength: 550 MPa, Elongation: 12%',
                'availability' => 'Available',
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 5,
            ],

            // ==================== CONSTRUCTION - MASONRY ====================
            [
                'name' => 'First Class Red Bricks',
                'description' => 'Premium quality clay bricks for load-bearing walls. Uniform color, sharp edges, and high compressive strength.',
                'category' => 'Construction',
                'type' => 'Masonry',
                'price_per_unit' => 18,
                'unit' => 'piece',
                'color' => '#A0522D',
                'brand' => 'Bhaktapur Kilns',
                'specifications' => 'Size: 9"×4.5"×3", Strength: 10-12 MPa',
                'availability' => 'Available',
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 6,
            ],
            [
                'name' => 'Concrete Hollow Blocks',
                'description' => 'Lightweight hollow concrete blocks for faster construction. Better thermal insulation.',
                'category' => 'Construction',
                'type' => 'Masonry',
                'price_per_unit' => 45,
                'unit' => 'piece',
                'color' => '#808080',
                'brand' => 'Local Manufacturer',
                'specifications' => 'Size: 16"×8"×8", 2 hollow cores',
                'availability' => 'Available',
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 7,
            ],
            [
                'name' => 'AAC Blocks (Autoclave Aerated)',
                'description' => 'Lightweight aerated concrete blocks. Excellent thermal insulation and fire resistance.',
                'category' => 'Construction',
                'type' => 'Masonry',
                'price_per_unit' => 55,
                'unit' => 'piece',
                'color' => '#F5F5F5',
                'brand' => 'Siporex',
                'specifications' => 'Density: 550-650 kg/m³, Size: 24"×8"×4"',
                'availability' => 'Available',
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 8,
            ],
            [
                'name' => 'Fly Ash Bricks',
                'description' => 'Eco-friendly bricks made from fly ash. Uniform size, smooth finish, lower water absorption.',
                'category' => 'Construction',
                'type' => 'Masonry',
                'price_per_unit' => 12,
                'unit' => 'piece',
                'color' => '#C0C0C0',
                'brand' => 'Green Build',
                'specifications' => 'Size: 9"×4"×3", Strength: 7-10 MPa',
                'availability' => 'Available',
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 9,
            ],

            // ==================== CONSTRUCTION - BINDING ====================
            [
                'name' => 'OPC Cement 53 Grade',
                'description' => 'Ordinary Portland Cement for general construction. High early strength development.',
                'category' => 'Construction',
                'type' => 'Binding',
                'price_per_unit' => 850,
                'unit' => 'bag (50kg)',
                'color' => '#808080',
                'brand' => 'Shivam Cement',
                'specifications' => '53 Grade, IS 12269 compliant',
                'availability' => 'Available',
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 10,
            ],
            [
                'name' => 'PPC Cement',
                'description' => 'Portland Pozzolana Cement for durable construction. Better resistance to sulphate attack.',
                'category' => 'Construction',
                'type' => 'Binding',
                'price_per_unit' => 800,
                'unit' => 'bag (50kg)',
                'color' => '#696969',
                'brand' => 'Hetauda Cement',
                'specifications' => 'IS 1489 Part 1 compliant',
                'availability' => 'Available',
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 11,
            ],
            [
                'name' => 'White Cement',
                'description' => 'Pure white cement for decorative applications. Ideal for tile joints and wall putty.',
                'category' => 'Construction',
                'type' => 'Binding',
                'price_per_unit' => 35,
                'unit' => 'kg',
                'color' => '#FFFFFF',
                'brand' => 'Birla White',
                'specifications' => 'Whiteness: 87%, Fineness: 350 m²/kg',
                'availability' => 'Available',
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 12,
            ],
            [
                'name' => 'River Sand (Fine)',
                'description' => 'Natural river sand for plastering and masonry. Clean, well-graded fine aggregate.',
                'category' => 'Construction',
                'type' => 'Aggregate',
                'price_per_unit' => 2800,
                'unit' => 'cu.m',
                'color' => '#C4A35A',
                'brand' => 'Natural',
                'specifications' => 'Zone II/III, Fineness modulus: 2.5-3.0',
                'availability' => 'Available',
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 13,
            ],
            [
                'name' => 'Crushed Stone Aggregate 20mm',
                'description' => 'Angular crushed stone for concrete work. Better bonding with cement paste.',
                'category' => 'Construction',
                'type' => 'Aggregate',
                'price_per_unit' => 1800,
                'unit' => 'cu.m',
                'color' => '#5A5A5A',
                'brand' => 'Local Crusher',
                'specifications' => 'Nominal size: 20mm, Specific gravity: 2.6-2.7',
                'availability' => 'Available',
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 14,
            ],

            // ==================== FLOORING - CERAMIC ====================
            [
                'name' => 'Vitrified Floor Tiles - Glossy White',
                'description' => 'Premium glazed vitrified tiles with high gloss finish. Low water absorption, scratch resistant.',
                'category' => 'Flooring',
                'type' => 'Ceramic',
                'price_per_unit' => 95,
                'unit' => 'sq.ft',
                'color' => '#FAFAFA',
                'brand' => 'Kajaria',
                'specifications' => 'Size: 2×2 ft, Thickness: 8mm, Finish: Polished',
                'availability' => 'Available',
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 15,
            ],
            [
                'name' => 'Vitrified Tiles - Marble Look',
                'description' => 'Digital printed tiles with realistic marble pattern. Elegant Statuario marble effect.',
                'category' => 'Flooring',
                'type' => 'Ceramic',
                'price_per_unit' => 120,
                'unit' => 'sq.ft',
                'color' => '#F8F8F8',
                'brand' => 'Somany',
                'specifications' => 'Size: 4×2 ft, HD Digital Print, Anti-bacterial',
                'availability' => 'Available',
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 16,
            ],
            [
                'name' => 'Porcelain Floor Tiles - Wood Finish',
                'description' => 'Wood-look porcelain tiles combining beauty of wood with durability of tiles.',
                'category' => 'Flooring',
                'type' => 'Ceramic',
                'price_per_unit' => 110,
                'unit' => 'sq.ft',
                'color' => '#8B6914',
                'brand' => 'Asian Granito',
                'specifications' => 'Size: 6"×36", Matte finish, PEI Rating: 4',
                'availability' => 'Available',
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 17,
            ],
            [
                'name' => 'Anti-Skid Bathroom Tiles',
                'description' => 'Textured ceramic tiles with anti-slip surface. Ideal for bathrooms and wet areas.',
                'category' => 'Flooring',
                'type' => 'Ceramic',
                'price_per_unit' => 65,
                'unit' => 'sq.ft',
                'color' => '#D3D3D3',
                'brand' => 'Nitco',
                'specifications' => 'Size: 12"×12", R11 Anti-slip rating',
                'availability' => 'Available',
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 18,
            ],
            [
                'name' => 'Kitchen Ceramic Tiles',
                'description' => 'Durable ceramic tiles for kitchen floors. Easy to clean, stain resistant.',
                'category' => 'Flooring',
                'type' => 'Ceramic',
                'price_per_unit' => 55,
                'unit' => 'sq.ft',
                'color' => '#F5F5DC',
                'brand' => 'Orient Bell',
                'specifications' => 'Size: 2×2 ft, Matt finish, Easy maintenance',
                'availability' => 'Available',
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 19,
            ],

            // ==================== FLOORING - NATURAL STONE ====================
            [
                'name' => 'Italian Marble - Statuario',
                'description' => 'Premium Italian Statuario marble with distinctive gray veining on white background.',
                'category' => 'Flooring',
                'type' => 'Natural Stone',
                'price_per_unit' => 650,
                'unit' => 'sq.ft',
                'color' => '#F5F5F5',
                'brand' => 'Imported Italy',
                'specifications' => 'Thickness: 18mm, Polished finish',
                'availability' => 'Limited Stock',
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 20,
            ],
            [
                'name' => 'Indian Marble - Makrana White',
                'description' => 'Classic Indian white marble from Rajasthan. Same variety used in Taj Mahal.',
                'category' => 'Flooring',
                'type' => 'Natural Stone',
                'price_per_unit' => 280,
                'unit' => 'sq.ft',
                'color' => '#FFFAFA',
                'brand' => 'Makrana',
                'specifications' => 'Thickness: 16-18mm, Mirror polish available',
                'availability' => 'Available',
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 21,
            ],
            [
                'name' => 'Black Granite - Absolute Black',
                'description' => 'Premium absolute black granite with uniform color. Elegant and timeless.',
                'category' => 'Flooring',
                'type' => 'Natural Stone',
                'price_per_unit' => 180,
                'unit' => 'sq.ft',
                'color' => '#0C0C0C',
                'brand' => 'South Indian',
                'specifications' => 'Thickness: 15-18mm, Mirror/Leather finish',
                'availability' => 'Available',
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 22,
            ],
            [
                'name' => 'Kota Stone - Natural',
                'description' => 'Durable limestone from Kota, Rajasthan. Ideal for outdoor and high-traffic areas.',
                'category' => 'Flooring',
                'type' => 'Natural Stone',
                'price_per_unit' => 45,
                'unit' => 'sq.ft',
                'color' => '#7B8B6F',
                'brand' => 'Kota Natural',
                'specifications' => 'Thickness: 20-25mm, Natural/Polish finish',
                'availability' => 'Available',
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 23,
            ],
            [
                'name' => 'Slate Stone - Grey',
                'description' => 'Natural slate stone with unique texture. Perfect for rustic and contemporary designs.',
                'category' => 'Flooring',
                'type' => 'Natural Stone',
                'price_per_unit' => 85,
                'unit' => 'sq.ft',
                'color' => '#708090',
                'brand' => 'Natural',
                'specifications' => 'Thickness: 10-15mm, Natural cleft surface',
                'availability' => 'Available',
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 24,
            ],

            // ==================== FLOORING - ENGINEERED ====================
            [
                'name' => 'Engineered Wood Flooring - Oak',
                'description' => 'Premium engineered wood with real oak veneer. Click-lock installation system.',
                'category' => 'Flooring',
                'type' => 'Engineered',
                'price_per_unit' => 280,
                'unit' => 'sq.ft',
                'color' => '#C19A6B',
                'brand' => 'Pergo',
                'specifications' => 'Thickness: 12mm, AC5 rating, 25-year warranty',
                'availability' => 'Available',
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 25,
            ],
            [
                'name' => 'Laminate Flooring - Walnut',
                'description' => 'High-quality laminate with realistic walnut wood grain. Scratch and fade resistant.',
                'category' => 'Flooring',
                'type' => 'Engineered',
                'price_per_unit' => 145,
                'unit' => 'sq.ft',
                'color' => '#5D4037',
                'brand' => 'Greenply',
                'specifications' => 'Thickness: 8mm, AC4 rating, Water resistant',
                'availability' => 'Available',
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 26,
            ],
            [
                'name' => 'SPC Vinyl Flooring',
                'description' => 'Stone polymer composite flooring. 100% waterproof, ideal for all rooms.',
                'category' => 'Flooring',
                'type' => 'Engineered',
                'price_per_unit' => 165,
                'unit' => 'sq.ft',
                'color' => '#A0826D',
                'brand' => 'Welspun',
                'specifications' => 'Thickness: 5mm, Waterproof core, UV coating',
                'availability' => 'Available',
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 27,
            ],
            [
                'name' => 'LVT Flooring - Stone Look',
                'description' => 'Luxury vinyl tiles with realistic stone appearance. Comfortable underfoot.',
                'category' => 'Flooring',
                'type' => 'Engineered',
                'price_per_unit' => 125,
                'unit' => 'sq.ft',
                'color' => '#8B8682',
                'brand' => 'Armstrong',
                'specifications' => 'Thickness: 3mm, Commercial grade, Easy maintenance',
                'availability' => 'Available',
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 28,
            ],

            // ==================== WALL FINISH - PAINT ====================
            [
                'name' => 'Asian Paints Royale Play',
                'description' => 'Premium texture paint for designer walls. Create unique patterns and effects.',
                'category' => 'Wall Finish',
                'type' => 'Paint',
                'price_per_unit' => 750,
                'unit' => 'liter',
                'color' => '#FFFFFF',
                'brand' => 'Asian Paints',
                'specifications' => 'Coverage: 30-40 sq.ft/L, Washable, Low VOC',
                'availability' => 'Available',
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 29,
            ],
            [
                'name' => 'Berger Silk Glamor',
                'description' => 'Luxury emulsion with silk-like sheen. Superior coverage and durability.',
                'category' => 'Wall Finish',
                'type' => 'Paint',
                'price_per_unit' => 650,
                'unit' => 'liter',
                'color' => '#FAF0E6',
                'brand' => 'Berger',
                'specifications' => 'Coverage: 120-140 sq.ft/L, Anti-fungal',
                'availability' => 'Available',
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 30,
            ],
            [
                'name' => 'Dulux Velvet Touch',
                'description' => 'Ultra-smooth interior paint with soft matte finish. Stain resistant technology.',
                'category' => 'Wall Finish',
                'type' => 'Paint',
                'price_per_unit' => 700,
                'unit' => 'liter',
                'color' => '#F5F5F5',
                'brand' => 'Dulux',
                'specifications' => 'Coverage: 130-150 sq.ft/L, 5000+ colors',
                'availability' => 'Available',
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 31,
            ],
            [
                'name' => 'Nippon Paint Weatherbond',
                'description' => 'Premium exterior paint with weather protection. UV resistant, anti-algal.',
                'category' => 'Wall Finish',
                'type' => 'Paint',
                'price_per_unit' => 550,
                'unit' => 'liter',
                'color' => '#E8E8E8',
                'brand' => 'Nippon',
                'specifications' => 'Coverage: 100-120 sq.ft/L, 7-year warranty',
                'availability' => 'Available',
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 32,
            ],
            [
                'name' => 'Wall Putty - White Cement Based',
                'description' => 'Premium wall putty for smooth base coat. Enhances paint finish and durability.',
                'category' => 'Wall Finish',
                'type' => 'Paint',
                'price_per_unit' => 45,
                'unit' => 'kg',
                'color' => '#FFFFFF',
                'brand' => 'Birla Wall Care',
                'specifications' => 'Coverage: 20-25 sq.ft/kg, Water resistant',
                'availability' => 'Available',
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 33,
            ],

            // ==================== WALL FINISH - WALLPAPER ====================
            [
                'name' => '3D Brick Wallpaper',
                'description' => 'Self-adhesive 3D textured wallpaper with realistic brick pattern. Easy to apply and remove.',
                'category' => 'Wall Finish',
                'type' => 'Wallpaper',
                'price_per_unit' => 180,
                'unit' => 'sq.ft',
                'color' => '#CD853F',
                'brand' => 'Decorative Arts',
                'specifications' => 'Thickness: 3mm, PE foam, Waterproof',
                'availability' => 'Available',
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 34,
            ],
            [
                'name' => 'Floral Pattern Wallpaper',
                'description' => 'Elegant floral design wallpaper for bedrooms. Non-woven material for easy installation.',
                'category' => 'Wall Finish',
                'type' => 'Wallpaper',
                'price_per_unit' => 120,
                'unit' => 'sq.ft',
                'color' => '#FFC0CB',
                'brand' => 'Nilaya',
                'specifications' => 'Roll size: 57 sq.ft, Paste the wall type',
                'availability' => 'Available',
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 35,
            ],
            [
                'name' => 'Geometric Pattern Wallpaper',
                'description' => 'Modern geometric design for contemporary interiors. Vinyl coated for easy cleaning.',
                'category' => 'Wall Finish',
                'type' => 'Wallpaper',
                'price_per_unit' => 150,
                'unit' => 'sq.ft',
                'color' => '#2F4F4F',
                'brand' => 'Marshalls',
                'specifications' => 'Roll size: 57 sq.ft, Washable, Fire retardant',
                'availability' => 'Available',
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 36,
            ],
            [
                'name' => 'Wood Panel Wallpaper',
                'description' => 'Realistic wood panel effect wallpaper. Creates warm, rustic ambiance.',
                'category' => 'Wall Finish',
                'type' => 'Wallpaper',
                'price_per_unit' => 135,
                'unit' => 'sq.ft',
                'color' => '#8B4513',
                'brand' => 'Decorative Arts',
                'specifications' => 'HD print, Eco-friendly material',
                'availability' => 'Available',
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 37,
            ],

            // ==================== WALL FINISH - STONE CLADDING ====================
            [
                'name' => 'Natural Stone Cladding - Grey',
                'description' => 'Natural stone veneer for exterior and interior walls. Adds character and texture.',
                'category' => 'Wall Finish',
                'type' => 'Stone',
                'price_per_unit' => 250,
                'unit' => 'sq.ft',
                'color' => '#808080',
                'brand' => 'Stone World',
                'specifications' => 'Thickness: 15-25mm, Random pattern',
                'availability' => 'Available',
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 38,
            ],
            [
                'name' => 'Marble Wall Cladding',
                'description' => 'Italian marble slabs for luxury wall finish. Perfect for feature walls and bathrooms.',
                'category' => 'Wall Finish',
                'type' => 'Stone',
                'price_per_unit' => 450,
                'unit' => 'sq.ft',
                'color' => '#F8F8F8',
                'brand' => 'Imported',
                'specifications' => 'Thickness: 18mm, Book-matched available',
                'availability' => 'Limited Stock',
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 39,
            ],
            [
                'name' => 'Slate Wall Tiles',
                'description' => 'Natural slate tiles for accent walls. Unique texture with earthy tones.',
                'category' => 'Wall Finish',
                'type' => 'Stone',
                'price_per_unit' => 165,
                'unit' => 'sq.ft',
                'color' => '#36454F',
                'brand' => 'Natural',
                'specifications' => 'Thickness: 10mm, Natural cleft finish',
                'availability' => 'Available',
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 40,
            ],

            // ==================== WALL FINISH - PANELS ====================
            [
                'name' => 'WPC Wall Panels',
                'description' => 'Wood-plastic composite wall panels. Waterproof, termite-proof, zero maintenance.',
                'category' => 'Wall Finish',
                'type' => 'Panel',
                'price_per_unit' => 85,
                'unit' => 'sq.ft',
                'color' => '#D2691E',
                'brand' => 'Greenpanel',
                'specifications' => 'Size: 10"×10ft, Tongue & groove, UV resistant',
                'availability' => 'Available',
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 41,
            ],
            [
                'name' => 'PVC Wall Panels - 3D Design',
                'description' => 'Decorative PVC panels with 3D patterns. Lightweight and easy to install.',
                'category' => 'Wall Finish',
                'type' => 'Panel',
                'price_per_unit' => 45,
                'unit' => 'sq.ft',
                'color' => '#FFFFFF',
                'brand' => 'Decorative',
                'specifications' => 'Thickness: 8mm, Waterproof, Fire retardant',
                'availability' => 'Available',
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 42,
            ],
            [
                'name' => 'Acoustic Wall Panels',
                'description' => 'Sound-absorbing fabric panels for home theaters and studios. NRC: 0.85.',
                'category' => 'Wall Finish',
                'type' => 'Panel',
                'price_per_unit' => 350,
                'unit' => 'sq.ft',
                'color' => '#4A4A4A',
                'brand' => 'Sonex',
                'specifications' => 'Size: 2×4 ft, Fabric wrapped, Class A fire rated',
                'availability' => 'Available',
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 43,
            ],
            [
                'name' => 'Charcoal Panel - Decorative',
                'description' => 'Activated charcoal panels for unique texture. Also helps in air purification.',
                'category' => 'Wall Finish',
                'type' => 'Panel',
                'price_per_unit' => 180,
                'unit' => 'sq.ft',
                'color' => '#2C2C2C',
                'brand' => 'Eco Panel',
                'specifications' => 'Natural charcoal, Air purifying properties',
                'availability' => 'Limited Stock',
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 44,
            ],

            // ==================== COLOR PALETTE ====================
            [
                'name' => 'Modern Minimalist Palette',
                'description' => 'Clean, neutral color scheme perfect for contemporary spaces. Whites, grays, and black accents.',
                'category' => 'Color Palette',
                'type' => 'Interior',
                'price_per_unit' => 0,
                'unit' => 'set',
                'color' => '#FFFFFF,#F5F5F5,#808080,#000000',
                'brand' => 'Designer Collection',
                'specifications' => 'Primary: White, Secondary: Soft Gray, Accent: Black',
                'availability' => 'Always Available',
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 45,
            ],
            [
                'name' => 'Warm Earth Tones',
                'description' => 'Cozy palette inspired by nature. Terracotta, beige, warm browns, and cream.',
                'category' => 'Color Palette',
                'type' => 'Interior',
                'price_per_unit' => 0,
                'unit' => 'set',
                'color' => '#E2725B,#F5F5DC,#8B4513,#FFFDD0',
                'brand' => 'Designer Collection',
                'specifications' => 'Primary: Terracotta, Secondary: Beige, Accent: Brown',
                'availability' => 'Always Available',
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 46,
            ],
            [
                'name' => 'Cool Coastal Blues',
                'description' => 'Refreshing palette reminiscent of ocean and sky. Various shades of blue with white.',
                'category' => 'Color Palette',
                'type' => 'Interior',
                'price_per_unit' => 0,
                'unit' => 'set',
                'color' => '#000080,#87CEEB,#E0FFFF,#FFFFFF',
                'brand' => 'Designer Collection',
                'specifications' => 'Primary: Navy, Secondary: Sky Blue, Accent: White',
                'availability' => 'Always Available',
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 47,
            ],
            [
                'name' => 'Scandinavian Light',
                'description' => 'Nordic-inspired palette with focus on light. Soft whites, pale wood tones, muted pastels.',
                'category' => 'Color Palette',
                'type' => 'Interior',
                'price_per_unit' => 0,
                'unit' => 'set',
                'color' => '#FAFAF0,#E8DCC4,#B0C4DE,#98D8C8',
                'brand' => 'Designer Collection',
                'specifications' => 'Primary: Off-white, Secondary: Light wood, Accent: Soft pastel',
                'availability' => 'Always Available',
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 48,
            ],
            [
                'name' => 'Bold & Dramatic',
                'description' => 'High-contrast palette for statement spaces. Deep jewel tones with metallic accents.',
                'category' => 'Color Palette',
                'type' => 'Interior',
                'price_per_unit' => 0,
                'unit' => 'set',
                'color' => '#191970,#50C878,#FFD700,#800020',
                'brand' => 'Designer Collection',
                'specifications' => 'Primary: Deep Blue, Secondary: Emerald, Accent: Gold',
                'availability' => 'Always Available',
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 49,
            ],
            [
                'name' => 'Traditional Nepali',
                'description' => 'Colors inspired by Nepali heritage. Rich reds, deep maroons, and golden accents.',
                'category' => 'Color Palette',
                'type' => 'Interior',
                'price_per_unit' => 0,
                'unit' => 'set',
                'color' => '#DC143C,#800000,#FFD700,#FFFDD0',
                'brand' => 'Heritage Collection',
                'specifications' => 'Primary: Crimson Red, Secondary: Maroon, Accent: Gold',
                'availability' => 'Always Available',
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 50,
            ],
            [
                'name' => 'Urban Industrial',
                'description' => 'Raw, edgy palette for loft-style spaces. Exposed concrete, brick, and metal tones.',
                'category' => 'Color Palette',
                'type' => 'Interior',
                'price_per_unit' => 0,
                'unit' => 'set',
                'color' => '#808080,#A0522D,#2F4F4F,#000000',
                'brand' => 'Designer Collection',
                'specifications' => 'Primary: Concrete Gray, Secondary: Rust, Accent: Dark Metal',
                'availability' => 'Always Available',
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 51,
            ],
            [
                'name' => 'Pastel Dreams',
                'description' => 'Soft, soothing palette for bedrooms and nurseries. Gentle pinks, blues, and lavenders.',
                'category' => 'Color Palette',
                'type' => 'Interior',
                'price_per_unit' => 0,
                'unit' => 'set',
                'color' => '#FFB6C1,#E6E6FA,#B0E0E6,#FFFDD0',
                'brand' => 'Designer Collection',
                'specifications' => 'Primary: Soft Pink, Secondary: Lavender, Accent: Powder Blue',
                'availability' => 'Always Available',
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 52,
            ],
            [
                'name' => 'Forest Green',
                'description' => 'Nature-inspired greens for biophilic design. Various shades of green with wood tones.',
                'category' => 'Color Palette',
                'type' => 'Interior',
                'price_per_unit' => 0,
                'unit' => 'set',
                'color' => '#228B22,#90EE90,#8B4513,#FFFDD0',
                'brand' => 'Designer Collection',
                'specifications' => 'Primary: Forest Green, Secondary: Sage, Accent: Wood Brown',
                'availability' => 'Always Available',
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 53,
            ],
            [
                'name' => 'Monochromatic Gray',
                'description' => 'Sophisticated gray-scale palette. Multiple shades of gray for depth and interest.',
                'category' => 'Color Palette',
                'type' => 'Interior',
                'price_per_unit' => 0,
                'unit' => 'set',
                'color' => '#D3D3D3,#A9A9A9,#696969,#2F4F4F',
                'brand' => 'Designer Collection',
                'specifications' => 'Primary: Light Gray, Secondary: Medium Gray, Accent: Charcoal',
                'availability' => 'Always Available',
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 54,
            ],

            // ==================== ADDITIONAL CONSTRUCTION MATERIALS ====================
            [
                'name' => 'Waterproofing Membrane',
                'description' => 'Bituminous waterproofing membrane for roofs and basements. Self-adhesive application.',
                'category' => 'Construction',
                'type' => 'Waterproofing',
                'price_per_unit' => 120,
                'unit' => 'sq.ft',
                'color' => '#000000',
                'brand' => 'Fosroc',
                'specifications' => 'Thickness: 3mm, APP modified bitumen',
                'availability' => 'Available',
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 55,
            ],
            [
                'name' => 'Roof Tiles - Mangalore Pattern',
                'description' => 'Traditional clay roof tiles. Natural cooling properties, durable for decades.',
                'category' => 'Construction',
                'type' => 'Roofing',
                'price_per_unit' => 35,
                'unit' => 'piece',
                'color' => '#A0522D',
                'brand' => 'Wienerberger',
                'specifications' => 'Size: 16"×9", Traditional wave pattern',
                'availability' => 'Available',
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 56,
            ],
            [
                'name' => 'GI Roofing Sheets',
                'description' => 'Galvanized iron roofing sheets. Corrosion resistant, long-lasting protection.',
                'category' => 'Construction',
                'type' => 'Roofing',
                'price_per_unit' => 65,
                'unit' => 'sq.ft',
                'color' => '#C0C0C0',
                'brand' => 'Tata Steel',
                'specifications' => 'Thickness: 0.5mm, Zinc coating: 275 GSM',
                'availability' => 'Available',
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 57,
            ],
            [
                'name' => 'Insulation Board - XPS',
                'description' => 'Extruded polystyrene insulation for walls and roofs. High R-value, moisture resistant.',
                'category' => 'Construction',
                'type' => 'Insulation',
                'price_per_unit' => 55,
                'unit' => 'sq.ft',
                'color' => '#87CEEB',
                'brand' => 'Dow',
                'specifications' => 'Thickness: 50mm, R-value: 10, Closed cell',
                'availability' => 'Available',
                'is_active' => true,
                'is_featured' => false,
                'sort_order' => 58,
            ],
            [
                'name' => 'Gypsum Board - Standard',
                'description' => 'Standard gypsum board for false ceilings and partitions. Fire resistant, easy to finish.',
                'category' => 'Construction',
                'type' => 'Finishing',
                'price_per_unit' => 35,
                'unit' => 'sq.ft',
                'color' => '#F5F5F5',
                'brand' => 'Gyproc',
                'specifications' => 'Thickness: 12.5mm, Size: 4×8 ft',
                'availability' => 'Available',
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 59,
            ],
            [
                'name' => 'Plywood - BWR Grade',
                'description' => 'Boiling water resistant plywood for furniture and interiors. Termite treated.',
                'category' => 'Construction',
                'type' => 'Wood',
                'price_per_unit' => 95,
                'unit' => 'sq.ft',
                'color' => '#DEB887',
                'brand' => 'Century Ply',
                'specifications' => 'Thickness: 18mm, Size: 8×4 ft, IS 303 Grade',
                'availability' => 'Available',
                'is_active' => true,
                'is_featured' => true,
                'sort_order' => 60,
            ],
        ];

        foreach ($materials as $item) {
            Material::create($item);
        }
    }
}
