import type {
    FurnitureItem,
    InteriorCatalog,
    InteriorRoomTemplate,
    LightingPreset,
    MaterialPalette,
    MoodboardItem,
    RoomTemplateId,
} from '@/types/interior-design';

const MATERIAL_LIBRARY: MaterialPalette[] = [
  {
    id: 'earthy-lounge',
    name: 'Earthy Lounge',
    floor: '#b38358',
    wall: '#f6efe2',
    accent: '#d97757',
    lighting: '#facc15',
    description: 'Walnut plank flooring with ivory stucco walls and copper accents.',
    mood: 'Warm',
    appliesTo: ['living', 'dining', 'study'],
  },
  {
    id: 'midnight-minimal',
    name: 'Midnight Minimal',
    floor: '#1f2933',
    wall: '#e5e7eb',
    accent: '#64748b',
    lighting: '#38bdf8',
    description: 'Charcoal slate tiles, soft white walls, and brushed steel hardware.',
    mood: 'Cool',
    appliesTo: ['living', 'study', 'kitchen', 'any'],
  },
  {
    id: 'spa-retreat',
    name: 'Spa Retreat',
    floor: '#a7c7a1',
    wall: '#f8faf5',
    accent: '#6b8f71',
    lighting: '#f8d477',
    description: 'Matte sage stone, limewash walls, and brushed brass fittings.',
    mood: 'Neutral',
    appliesTo: ['bathroom', 'bedroom'],
  },
  {
    id: 'artisan-kitchen',
    name: 'Artisan Kitchen',
    floor: '#d6a15d',
    wall: '#fdf3ea',
    accent: '#b45309',
    lighting: '#fbbf24',
    description: 'Terracotta chevron floors with plaster finish and teak cabinetry.',
    mood: 'Warm',
    appliesTo: ['kitchen', 'dining'],
  },
  {
    id: 'nebula-suite',
    name: 'Nebula Suite',
    floor: '#4c51bf',
    wall: '#eef2ff',
    accent: '#a855f7',
    lighting: '#c084fc',
    description: 'Midnight indigo carpet with lavender accents and soft diffused lighting.',
    mood: 'Cool',
    appliesTo: ['bedroom', 'study'],
  },
  {
    id: 'gallery-white',
    name: 'Gallery White',
    floor: '#d1d5db',
    wall: '#ffffff',
    accent: '#111827',
    lighting: '#e5e7eb',
    description: 'Polished concrete floor, gallery-white walls, and matte black hardware.',
    mood: 'Neutral',
    appliesTo: ['any'],
  },
];

const LIGHTING_LIBRARY: LightingPreset[] = [
  {
    id: 'golden-hour',
    name: 'Golden Hour',
    temperature: '3000K',
    brightness: '70%',
    tint: '#fbbf24',
    description: 'Warm ambient wash paired with soft uplights for hospitality spaces.',
  },
  {
    id: 'studio-daylight',
    name: 'Studio Daylight',
    temperature: '5000K',
    brightness: '85%',
    tint: '#60a5fa',
    description: 'High CRI daylight for kitchens, creative studios, and product shoots.',
  },
  {
    id: 'twilight',
    name: 'Twilight Glow',
    temperature: '2700K',
    brightness: '55%',
    tint: '#fda4af',
    description: 'Layered sconces and concealed coves tuned for relaxed evening rituals.',
  },
  {
    id: 'gallery-track',
    name: 'Gallery Track',
    temperature: '4000K',
    brightness: '65%',
    tint: '#a6e3e9',
    description: 'Directional beams with accent dimmers to highlight curated vignettes.',
  },
];

// Furniture sizes in meters (width x length x height)
const FURNITURE_LIBRARY: FurnitureItem[] = [
  // === SEATING ===
  {
    id: 'sofa-3seat',
    name: '3-Seater Sofa',
    category: 'Seating',
    style: 'Modern',
    width: 2.2,
    length: 0.9,
    height: 0.85,
    price: 45000,
    suitableFor: ['living'],
    color: '#6b7280',
    finish: 'Fabric upholstery with wooden legs',
    image: '/images/furniture/seating/sofa-3seat.svg',
  },
  {
    id: 'sofa-2seat',
    name: '2-Seater Loveseat',
    category: 'Seating',
    style: 'Modern',
    width: 1.5,
    length: 0.85,
    height: 0.8,
    price: 32000,
    suitableFor: ['living', 'bedroom'],
    color: '#9ca3af',
    finish: 'Linen fabric with metal frame',
    image: '/images/furniture/seating/sofa-2seat.svg',
  },
  {
    id: 'armchair-01',
    name: 'Accent Armchair',
    category: 'Seating',
    style: 'Contemporary',
    width: 0.8,
    length: 0.85,
    height: 0.9,
    price: 18000,
    suitableFor: ['living', 'bedroom', 'study'],
    color: '#d97706',
    finish: 'Velvet upholstery with wood frame',
    image: '/images/furniture/seating/armchair.svg',
  },
  {
    id: 'dining-chair',
    name: 'Dining Chair',
    category: 'Seating',
    style: 'Classic',
    width: 0.45,
    length: 0.5,
    height: 0.9,
    price: 8000,
    suitableFor: ['dining', 'kitchen'],
    color: '#78350f',
    finish: 'Solid wood with cushioned seat',
    image: '/images/furniture/seating/dining-chair.svg',
  },
  {
    id: 'office-chair',
    name: 'Office Chair',
    category: 'Seating',
    style: 'Ergonomic',
    width: 0.65,
    length: 0.65,
    height: 1.1,
    price: 15000,
    suitableFor: ['study', 'any'],
    color: '#1f2937',
    finish: 'Mesh back with adjustable height',
    image: '/images/furniture/seating/office-chair.svg',
  },
  {
    id: 'bar-stool',
    name: 'Bar Stool',
    category: 'Seating',
    style: 'Industrial',
    width: 0.4,
    length: 0.4,
    height: 0.75,
    price: 6000,
    suitableFor: ['kitchen', 'dining'],
    color: '#374151',
    finish: 'Metal frame with wooden seat',
    image: '/images/furniture/seating/bar-stool.svg',
  },

  // === TABLES ===
  {
    id: 'dining-table-6',
    name: '6-Seater Dining Table',
    category: 'Tables',
    style: 'Contemporary',
    width: 1.8,
    length: 0.9,
    height: 0.75,
    price: 35000,
    suitableFor: ['dining'],
    color: '#92400e',
    finish: 'Solid oak with natural finish',
    image: '/images/furniture/tables/dining-table-6.svg',
  },
  {
    id: 'dining-table-4',
    name: '4-Seater Dining Table',
    category: 'Tables',
    style: 'Modern',
    width: 1.2,
    length: 0.8,
    height: 0.75,
    price: 25000,
    suitableFor: ['dining', 'kitchen'],
    color: '#78350f',
    finish: 'Walnut veneer top',
    image: '/images/furniture/tables/dining-table-4.svg',
  },
  {
    id: 'coffee-table',
    name: 'Coffee Table',
    category: 'Tables',
    style: 'Modern',
    width: 1.2,
    length: 0.6,
    height: 0.45,
    price: 12000,
    suitableFor: ['living'],
    color: '#44403c',
    finish: 'Tempered glass with metal frame',
    image: '/images/furniture/tables/coffee-table.svg',
  },
  {
    id: 'side-table',
    name: 'Side Table',
    category: 'Tables',
    style: 'Minimalist',
    width: 0.5,
    length: 0.5,
    height: 0.55,
    price: 5000,
    suitableFor: ['living', 'bedroom', 'any'],
    color: '#fbbf24',
    finish: 'Powder-coated steel',
    image: '/images/furniture/tables/side-table.svg',
  },
  {
    id: 'study-desk',
    name: 'Study Desk',
    category: 'Tables',
    style: 'Scandinavian',
    width: 1.4,
    length: 0.7,
    height: 0.75,
    price: 22000,
    suitableFor: ['study', 'bedroom'],
    color: '#fef3c7',
    finish: 'Birch plywood with white legs',
    image: '/images/furniture/tables/study-desk.svg',
  },
  {
    id: 'console-table',
    name: 'Console Table',
    category: 'Tables',
    style: 'Classic',
    width: 1.2,
    length: 0.35,
    height: 0.8,
    price: 18000,
    suitableFor: ['living', 'any'],
    color: '#1c1917',
    finish: 'Black lacquer with brass accents',
    image: '/images/furniture/tables/console-table.svg',
  },

  // === BEDS ===
  {
    id: 'bed-king',
    name: 'King Size Bed',
    category: 'Beds',
    style: 'Modern',
    width: 2.0,
    length: 2.1,
    height: 1.1,
    price: 55000,
    suitableFor: ['bedroom'],
    color: '#e5e7eb',
    finish: 'Upholstered headboard with storage',
    image: '/images/furniture/beds/bed-king.svg',
  },
  {
    id: 'bed-queen',
    name: 'Queen Size Bed',
    category: 'Beds',
    style: 'Contemporary',
    width: 1.6,
    length: 2.0,
    height: 1.0,
    price: 42000,
    suitableFor: ['bedroom'],
    color: '#d1d5db',
    finish: 'Wooden frame with fabric headboard',
    image: '/images/furniture/beds/bed-queen.svg',
  },
  {
    id: 'bed-single',
    name: 'Single Bed',
    category: 'Beds',
    style: 'Simple',
    width: 1.0,
    length: 2.0,
    height: 0.9,
    price: 18000,
    suitableFor: ['bedroom'],
    color: '#f3f4f6',
    finish: 'Metal frame with wooden slats',
    image: '/images/furniture/beds/bed-single.svg',
  },

  // === STORAGE ===
  {
    id: 'wardrobe-2door',
    name: '2-Door Wardrobe',
    category: 'Storage',
    style: 'Modern',
    width: 1.0,
    length: 0.6,
    height: 2.0,
    price: 28000,
    suitableFor: ['bedroom'],
    color: '#f5f5f4',
    finish: 'Laminate with soft-close hinges',
    image: '/images/furniture/storage/wardrobe-2door.svg',
  },
  {
    id: 'wardrobe-3door',
    name: '3-Door Wardrobe',
    category: 'Storage',
    style: 'Contemporary',
    width: 1.5,
    length: 0.6,
    height: 2.1,
    price: 42000,
    suitableFor: ['bedroom'],
    color: '#e7e5e4',
    finish: 'Sliding doors with mirror panel',
    image: '/images/furniture/storage/wardrobe-3door.svg',
  },
  {
    id: 'bookshelf',
    name: 'Bookshelf',
    category: 'Storage',
    style: 'Classic',
    width: 0.9,
    length: 0.3,
    height: 1.8,
    price: 15000,
    suitableFor: ['living', 'study', 'any'],
    color: '#78350f',
    finish: 'Solid wood with 5 shelves',
    image: '/images/furniture/storage/bookshelf.svg',
  },
  {
    id: 'tv-unit',
    name: 'TV Unit',
    category: 'Storage',
    style: 'Modern',
    width: 1.8,
    length: 0.45,
    height: 0.5,
    price: 22000,
    suitableFor: ['living', 'bedroom'],
    color: '#1f2937',
    finish: 'Matte finish with cable management',
    image: '/images/furniture/storage/tv-unit.svg',
  },
  {
    id: 'chest-drawers',
    name: 'Chest of Drawers',
    category: 'Storage',
    style: 'Classic',
    width: 0.8,
    length: 0.45,
    height: 1.0,
    price: 18000,
    suitableFor: ['bedroom', 'any'],
    color: '#a8a29e',
    finish: 'Wood with brass handles',
    image: '/images/furniture/storage/chest-drawers.svg',
  },
  {
    id: 'shoe-rack',
    name: 'Shoe Rack',
    category: 'Storage',
    style: 'Minimalist',
    width: 0.8,
    length: 0.3,
    height: 0.9,
    price: 6000,
    suitableFor: ['any'],
    color: '#57534e',
    finish: 'Metal frame with wooden shelves',
    image: '/images/furniture/storage/shoe-rack.svg',
  },

  // === KITCHEN ===
  {
    id: 'kitchen-island',
    name: 'Kitchen Island',
    category: 'Kitchen',
    style: 'Modern',
    width: 1.5,
    length: 0.8,
    height: 0.9,
    price: 45000,
    suitableFor: ['kitchen'],
    color: '#f3f4f6',
    finish: 'Quartz top with storage cabinets',
    image: '/images/furniture/kitchen/kitchen-island.svg',
  },
  {
    id: 'kitchen-cabinet',
    name: 'Kitchen Cabinet',
    category: 'Kitchen',
    style: 'Contemporary',
    width: 0.6,
    length: 0.6,
    height: 2.0,
    price: 15000,
    suitableFor: ['kitchen'],
    color: '#fafaf9',
    finish: 'Laminate with soft-close drawers',
    image: '/images/furniture/kitchen/kitchen-cabinet.svg',
  },

  // === BATHROOM ===
  {
    id: 'vanity-single',
    name: 'Single Vanity',
    category: 'Bathroom',
    style: 'Modern',
    width: 0.8,
    length: 0.5,
    height: 0.85,
    price: 25000,
    suitableFor: ['bathroom'],
    color: '#f5f5f4',
    finish: 'Ceramic basin with storage',
    image: '/images/furniture/bathroom/vanity-single.svg',
  },
  {
    id: 'vanity-double',
    name: 'Double Vanity',
    category: 'Bathroom',
    style: 'Luxury',
    width: 1.4,
    length: 0.55,
    height: 0.85,
    price: 45000,
    suitableFor: ['bathroom'],
    color: '#e7e5e4',
    finish: 'Marble top with twin basins',
    image: '/images/furniture/bathroom/vanity-double.svg',
  },
  {
    id: 'bathtub',
    name: 'Freestanding Bathtub',
    category: 'Bathroom',
    style: 'Luxury',
    width: 1.7,
    length: 0.8,
    height: 0.6,
    price: 65000,
    suitableFor: ['bathroom'],
    color: '#ffffff',
    finish: 'Acrylic with chrome fixtures',
    image: '/images/furniture/bathroom/bathtub.svg',
  },
  {
    id: 'toilet-western',
    name: 'Western Toilet',
    category: 'Bathroom',
    style: 'Modern',
    width: 0.4,
    length: 0.65,
    height: 0.42,
    price: 18000,
    suitableFor: ['bathroom'],
    color: '#ffffff',
    finish: 'Ceramic with soft-close seat',
    image: '/images/furniture/bathroom/toilet-western.svg',
  },
  {
    id: 'toilet-wall-hung',
    name: 'Wall-Hung Toilet',
    category: 'Bathroom',
    style: 'Contemporary',
    width: 0.36,
    length: 0.54,
    height: 0.35,
    price: 28000,
    suitableFor: ['bathroom'],
    color: '#ffffff',
    finish: 'Rimless ceramic with concealed tank',
    image: '/images/furniture/bathroom/toilet-wall-hung.svg',
  },
  {
    id: 'shower-enclosure',
    name: 'Glass Shower Enclosure',
    category: 'Bathroom',
    style: 'Modern',
    width: 1.0,
    length: 1.0,
    height: 2.0,
    price: 45000,
    suitableFor: ['bathroom'],
    color: '#e5e7eb',
    finish: 'Tempered glass with chrome frame',
    image: '/images/furniture/bathroom/shower-enclosure.svg',
  },
  {
    id: 'shower-corner',
    name: 'Corner Shower Unit',
    category: 'Bathroom',
    style: 'Space-saving',
    width: 0.9,
    length: 0.9,
    height: 2.0,
    price: 35000,
    suitableFor: ['bathroom'],
    color: '#d4d4d8',
    finish: 'Curved glass with rain shower head',
    image: '/images/furniture/bathroom/shower-corner.svg',
  },
  {
    id: 'bathroom-cabinet',
    name: 'Bathroom Wall Cabinet',
    category: 'Bathroom',
    style: 'Modern',
    width: 0.6,
    length: 0.15,
    height: 0.7,
    price: 12000,
    suitableFor: ['bathroom'],
    color: '#f5f5f4',
    finish: 'Moisture-resistant MDF with mirror',
    image: '/images/furniture/bathroom/bathroom-cabinet.svg',
    mount: 'wall',
  },
  {
    id: 'medicine-cabinet',
    name: 'Medicine Cabinet',
    category: 'Bathroom',
    style: 'Classic',
    width: 0.5,
    length: 0.12,
    height: 0.65,
    price: 8000,
    suitableFor: ['bathroom'],
    color: '#e7e5e4',
    finish: 'Mirrored door with interior shelves',
    image: '/images/furniture/bathroom/medicine-cabinet.svg',
    mount: 'wall',
  },
  {
    id: 'towel-rack',
    name: 'Heated Towel Rack',
    category: 'Bathroom',
    style: 'Modern',
    width: 0.6,
    length: 0.1,
    height: 0.8,
    price: 15000,
    suitableFor: ['bathroom'],
    color: '#a1a1aa',
    finish: 'Stainless steel with electric heating',
    image: '/images/furniture/bathroom/towel-rack.svg',
    mount: 'wall',
  },
  {
    id: 'towel-bar',
    name: 'Double Towel Bar',
    category: 'Bathroom',
    style: 'Classic',
    width: 0.6,
    length: 0.08,
    height: 0.15,
    price: 3500,
    suitableFor: ['bathroom'],
    color: '#c0c0c0',
    finish: 'Chrome-plated brass',
    image: '/images/furniture/bathroom/towel-bar.svg',
    mount: 'wall',
  },
  {
    id: 'bathroom-shelf',
    name: 'Glass Bathroom Shelf',
    category: 'Bathroom',
    style: 'Modern',
    width: 0.5,
    length: 0.12,
    height: 0.08,
    price: 2500,
    suitableFor: ['bathroom'],
    color: '#e5e7eb',
    finish: 'Tempered glass with chrome brackets',
    image: '/images/furniture/bathroom/bathroom-shelf.svg',
    mount: 'wall',
  },
  {
    id: 'toilet-paper-holder',
    name: 'Toilet Paper Holder',
    category: 'Bathroom',
    style: 'Modern',
    width: 0.15,
    length: 0.08,
    height: 0.12,
    price: 1500,
    suitableFor: ['bathroom'],
    color: '#a1a1aa',
    finish: 'Stainless steel wall mount',
    image: '/images/furniture/bathroom/toilet-paper-holder.svg',
    mount: 'wall',
  },
  {
    id: 'bathroom-mirror',
    name: 'LED Bathroom Mirror',
    category: 'Bathroom',
    style: 'Contemporary',
    width: 0.8,
    length: 0.05,
    height: 0.6,
    price: 18000,
    suitableFor: ['bathroom'],
    color: '#e5e7eb',
    finish: 'Anti-fog with LED backlight',
    image: '/images/furniture/bathroom/bathroom-mirror.svg',
    mount: 'wall',
  },
  {
    id: 'bidet',
    name: 'Floor-Mounted Bidet',
    category: 'Bathroom',
    style: 'European',
    width: 0.36,
    length: 0.56,
    height: 0.38,
    price: 22000,
    suitableFor: ['bathroom'],
    color: '#ffffff',
    finish: 'Ceramic with chrome mixer',
    image: '/images/furniture/bathroom/bidet.svg',
  },
  {
    id: 'bathroom-stool',
    name: 'Bathroom Stool',
    category: 'Bathroom',
    style: 'Modern',
    width: 0.35,
    length: 0.35,
    height: 0.45,
    price: 4500,
    suitableFor: ['bathroom'],
    color: '#f5f5f4',
    finish: 'Waterproof plastic with teak accent',
    image: '/images/furniture/bathroom/bathroom-stool.svg',
  },
  {
    id: 'laundry-basket',
    name: 'Laundry Hamper',
    category: 'Bathroom',
    style: 'Natural',
    width: 0.4,
    length: 0.35,
    height: 0.55,
    price: 3000,
    suitableFor: ['bathroom', 'bedroom'],
    color: '#d4a574',
    finish: 'Woven bamboo with fabric liner',
    image: '/images/furniture/bathroom/laundry-basket.svg',
  },
  {
    id: 'bathroom-scale',
    name: 'Digital Bathroom Scale',
    category: 'Bathroom',
    style: 'Modern',
    width: 0.3,
    length: 0.3,
    height: 0.03,
    price: 2500,
    suitableFor: ['bathroom'],
    color: '#1f2937',
    finish: 'Tempered glass with LED display',
    image: '/images/furniture/bathroom/bathroom-scale.svg',
  },
  {
    id: 'soap-dispenser',
    name: 'Automatic Soap Dispenser',
    category: 'Bathroom',
    style: 'Modern',
    width: 0.08,
    length: 0.08,
    height: 0.2,
    price: 2000,
    suitableFor: ['bathroom', 'kitchen'],
    color: '#a1a1aa',
    finish: 'Stainless steel touchless sensor',
    image: '/images/furniture/bathroom/soap-dispenser.svg',
  },
  {
    id: 'bath-mat',
    name: 'Bath Mat',
    category: 'Bathroom',
    style: 'Classic',
    width: 0.6,
    length: 0.4,
    height: 0.02,
    price: 1500,
    suitableFor: ['bathroom'],
    color: '#f5f5f4',
    finish: 'Memory foam with non-slip base',
    image: '/images/furniture/bathroom/bath-mat.svg',
  },

  // === LIGHTING ===
  {
    id: 'chandelier',
    name: 'Crystal Chandelier',
    category: 'Lighting',
    style: 'Classic',
    width: 0.8,
    length: 0.8,
    height: 0.9,
    price: 35000,
    suitableFor: ['living', 'dining'],
    color: '#fbbf24',
    finish: 'Crystal drops with gold frame',
    image: '/images/furniture/lighting/chandelier.svg',
    mount: 'ceiling',
  },
  {
    id: 'pendant-light',
    name: 'Pendant Light',
    category: 'Lighting',
    style: 'Modern',
    width: 0.4,
    length: 0.4,
    height: 0.35,
    price: 8000,
    suitableFor: ['kitchen', 'dining', 'any'],
    color: '#1f2937',
    finish: 'Matte black metal shade',
    image: '/images/furniture/lighting/pendant-light.svg',
    mount: 'ceiling',
  },
  {
    id: 'floor-lamp',
    name: 'Floor Lamp',
    category: 'Lighting',
    style: 'Scandinavian',
    width: 0.35,
    length: 0.35,
    height: 1.6,
    price: 12000,
    suitableFor: ['living', 'bedroom', 'study'],
    color: '#fef3c7',
    finish: 'Fabric shade with wooden tripod',
    image: '/images/furniture/lighting/floor-lamp.svg',
  },
  {
    id: 'table-lamp',
    name: 'Table Lamp',
    category: 'Lighting',
    style: 'Contemporary',
    width: 0.3,
    length: 0.3,
    height: 0.5,
    price: 5000,
    suitableFor: ['bedroom', 'study', 'living'],
    color: '#fcd34d',
    finish: 'Ceramic base with linen shade',
    image: '/images/furniture/lighting/table-lamp.svg',
  },
  {
    id: 'wall-sconce',
    name: 'Wall Sconce',
    category: 'Lighting',
    style: 'Modern',
    width: 0.15,
    length: 0.2,
    height: 0.25,
    price: 4000,
    suitableFor: ['bedroom', 'bathroom', 'any'],
    color: '#d4d4d8',
    finish: 'Brushed nickel with glass shade',
    image: '/images/furniture/lighting/wall-sconce.svg',
    mount: 'wall',
  },

  // === DECOR ===
  {
    id: 'area-rug',
    name: 'Area Rug (2x3m)',
    category: 'Decor',
    style: 'Modern',
    width: 2.0,
    length: 3.0,
    height: 0.02,
    price: 15000,
    suitableFor: ['living', 'bedroom', 'dining'],
    color: '#9ca3af',
    finish: 'Hand-woven wool blend',
    image: '/images/furniture/decor/area-rug.svg',
  },
  {
    id: 'plant-large',
    name: 'Indoor Plant (Large)',
    category: 'Decor',
    style: 'Natural',
    width: 0.6,
    length: 0.6,
    height: 1.5,
    price: 3500,
    suitableFor: ['living', 'any'],
    color: '#22c55e',
    finish: 'Fiddle leaf fig in ceramic pot',
    image: '/images/furniture/decor/plant-large.svg',
  },
  {
    id: 'plant-small',
    name: 'Indoor Plant (Small)',
    category: 'Decor',
    style: 'Natural',
    width: 0.25,
    length: 0.25,
    height: 0.4,
    price: 1200,
    suitableFor: ['any'],
    color: '#4ade80',
    finish: 'Succulent in terracotta pot',
    image: '/images/furniture/decor/plant-small.svg',
  },
  {
    id: 'mirror-wall',
    name: 'Wall Mirror',
    category: 'Decor',
    style: 'Classic',
    width: 0.8,
    length: 0.05,
    height: 1.2,
    price: 8000,
    suitableFor: ['bedroom', 'bathroom', 'any'],
    color: '#e5e7eb',
    finish: 'Gold frame with beveled edge',
    image: '/images/furniture/decor/mirror-wall.svg',
    mount: 'wall',
  },
  {
    id: 'artwork',
    name: 'Wall Art',
    category: 'Decor',
    style: 'Contemporary',
    width: 0.9,
    length: 0.03,
    height: 0.6,
    price: 5000,
    suitableFor: ['living', 'bedroom', 'any'],
    color: '#6366f1',
    finish: 'Canvas print with wooden frame',
    image: '/images/furniture/decor/artwork.svg',
    mount: 'wall',
  },
  {
    id: 'curtains',
    name: 'Curtain Panel',
    category: 'Decor',
    style: 'Classic',
    width: 1.5,
    length: 0.1,
    height: 2.5,
    price: 4500,
    suitableFor: ['living', 'bedroom', 'any'],
    color: '#d6d3d1',
    finish: 'Linen blend with blackout lining',
    image: '/images/furniture/decor/curtains.svg',
    mount: 'wall',
  },

  // Nepali Wall Art & Cultural Decor
  {
    id: 'painting-thangka-buddha',
    name: 'Thangka Buddha Painting',
    category: 'Decor',
    style: 'Nepali Traditional',
    width: 0.8,
    length: 0.03,
    height: 1.0,
    price: 18000,
    suitableFor: ['living', 'bedroom', 'any'],
    color: '#f97316',
    finish: 'Hand-painted silk thangka with brocade frame',
    image: '/images/furniture/decor/painting-thangka-buddha.svg',
    mount: 'wall',
  },
  {
    id: 'painting-himalayan-landscape',
    name: 'Himalayan Landscape Painting',
    category: 'Decor',
    style: 'Nepali Contemporary',
    width: 1.2,
    length: 0.03,
    height: 0.7,
    price: 16000,
    suitableFor: ['living', 'dining', 'any'],
    color: '#60a5fa',
    finish: 'Oil on canvas with wooden frame',
    image: '/images/furniture/decor/painting-himalayan-landscape.svg',
    mount: 'wall',
  },
  {
    id: 'painting-mandala',
    name: 'Sacred Mandala Art',
    category: 'Decor',
    style: 'Nepali Spiritual',
    width: 0.9,
    length: 0.03,
    height: 0.9,
    price: 14000,
    suitableFor: ['living', 'bedroom', 'study'],
    color: '#22c55e',
    finish: 'Hand-drawn mandala with gold detailing',
    image: '/images/furniture/decor/painting-mandala.svg',
    mount: 'wall',
  },
  {
    id: 'painting-nepali-village',
    name: 'Nepali Village Scene',
    category: 'Decor',
    style: 'Nepali Folk Art',
    width: 1.1,
    length: 0.03,
    height: 0.75,
    price: 12000,
    suitableFor: ['living', 'dining', 'any'],
    color: '#8B4513',
    finish: 'Acrylic on canvas depicting traditional village',
    image: '/images/furniture/decor/painting-nepali-village.svg',
    mount: 'wall',
  },
  {
    id: 'painting-village-life',
    name: 'Village Life Painting',
    category: 'Decor',
    style: 'Nepali Rural',
    width: 1.0,
    length: 0.03,
    height: 0.7,
    price: 10000,
    suitableFor: ['living', 'dining', 'any'],
    color: '#DAA520',
    finish: 'Traditional rural life scene with farmers',
    image: '/images/furniture/decor/painting-village-life.svg',
    mount: 'wall',
  },
  {
    id: 'painting-everest',
    name: 'Mount Everest Painting',
    category: 'Decor',
    style: 'Nepali Landscape',
    width: 1.3,
    length: 0.03,
    height: 0.8,
    price: 18000,
    suitableFor: ['living', 'study', 'any'],
    color: '#4169E1',
    finish: 'Majestic Everest peak oil painting',
    image: '/images/furniture/decor/painting-everest.svg',
    mount: 'wall',
  },
  {
    id: 'painting-annapurna',
    name: 'Annapurna Range Painting',
    category: 'Decor',
    style: 'Nepali Mountain',
    width: 1.4,
    length: 0.03,
    height: 0.7,
    price: 16000,
    suitableFor: ['living', 'bedroom', 'any'],
    color: '#87CEEB',
    finish: 'Panoramic Annapurna mountain view',
    image: '/images/furniture/decor/painting-annapurna.svg',
    mount: 'wall',
  },
  {
    id: 'painting-paubha',
    name: 'Paubha Art (Newari)',
    category: 'Decor',
    style: 'Newari Traditional',
    width: 0.7,
    length: 0.03,
    height: 0.9,
    price: 22000,
    suitableFor: ['living', 'bedroom', 'study'],
    color: '#DC143C',
    finish: 'Traditional Newari religious painting',
    image: '/images/furniture/decor/painting-paubha.svg',
    mount: 'wall',
  },
  {
    id: 'painting-pashupatinath',
    name: 'Pashupatinath Temple Art',
    category: 'Decor',
    style: 'Nepali Religious',
    width: 0.9,
    length: 0.03,
    height: 0.7,
    price: 15000,
    suitableFor: ['living', 'any'],
    color: '#CD853F',
    finish: 'Sacred temple scene painting',
    image: '/images/furniture/decor/painting-pashupatinath.svg',
    mount: 'wall',
  },
  {
    id: 'painting-kumari',
    name: 'Living Goddess Kumari Art',
    category: 'Decor',
    style: 'Nepali Cultural',
    width: 0.7,
    length: 0.03,
    height: 0.85,
    price: 20000,
    suitableFor: ['living', 'bedroom', 'any'],
    color: '#FF0000',
    finish: 'Portrait of the Living Goddess',
    image: '/images/furniture/decor/painting-kumari.svg',
    mount: 'wall',
  },
  {
    id: 'painting-rice-fields',
    name: 'Rice Terraces Painting',
    category: 'Decor',
    style: 'Nepali Agricultural',
    width: 1.2,
    length: 0.03,
    height: 0.65,
    price: 11000,
    suitableFor: ['living', 'dining', 'any'],
    color: '#32CD32',
    finish: 'Scenic rice paddy terraces',
    image: '/images/furniture/decor/painting-rice-fields.svg',
    mount: 'wall',
  },
  {
    id: 'painting-kathmandu-durbar',
    name: 'Kathmandu Durbar Square',
    category: 'Decor',
    style: 'Nepali Heritage',
    width: 1.1,
    length: 0.03,
    height: 0.7,
    price: 14000,
    suitableFor: ['living', 'study', 'any'],
    color: '#A0522D',
    finish: 'Historic durbar square architecture',
    image: '/images/furniture/decor/painting-kathmandu-durbar.svg',
    mount: 'wall',
  },
  {
    id: 'painting-newari-window',
    name: 'Traditional Newari Window',
    category: 'Decor',
    style: 'Newari Architecture',
    width: 0.6,
    length: 0.03,
    height: 0.8,
    price: 9000,
    suitableFor: ['living', 'bedroom', 'any'],
    color: '#8B0000',
    finish: 'Carved wooden window art piece',
    image: '/images/furniture/decor/painting-newari-window.svg',
    mount: 'wall',
  },
  {
    id: 'painting-prayer-flags',
    name: 'Prayer Flags Scene',
    category: 'Decor',
    style: 'Tibetan-Nepali',
    width: 1.0,
    length: 0.03,
    height: 0.6,
    price: 8000,
    suitableFor: ['living', 'bedroom', 'any'],
    color: '#FF6347',
    finish: 'Colorful prayer flags with mountain backdrop',
    image: '/images/furniture/decor/painting-prayer-flags.svg',
    mount: 'wall',
  },
  {
    id: 'painting-mithila',
    name: 'Mithila Art Painting',
    category: 'Decor',
    style: 'Mithila Folk',
    width: 0.8,
    length: 0.03,
    height: 0.8,
    price: 12000,
    suitableFor: ['living', 'bedroom', 'any'],
    color: '#FF4500',
    finish: 'Traditional Mithila folk art design',
    image: '/images/furniture/decor/painting-mithila.svg',
    mount: 'wall',
  },
  {
    id: 'painting-sherpa-life',
    name: 'Sherpa Mountain Life',
    category: 'Decor',
    style: 'Nepali Ethnic',
    width: 1.0,
    length: 0.03,
    height: 0.7,
    price: 13000,
    suitableFor: ['living', 'study', 'any'],
    color: '#4682B4',
    finish: 'Sherpa community and mountain life',
    image: '/images/furniture/decor/painting-sherpa-life.svg',
    mount: 'wall',
  },
  {
    id: 'painting-peacock-window',
    name: 'Peacock Window Art',
    category: 'Decor',
    style: 'Newari Masterpiece',
    width: 0.65,
    length: 0.03,
    height: 0.85,
    price: 25000,
    suitableFor: ['living', 'any'],
    color: '#006400',
    finish: 'Famous Bhaktapur peacock window replica',
    image: '/images/furniture/decor/painting-peacock-window.svg',
    mount: 'wall',
  },

  // === DOORS & WINDOWS ===
  {
    id: 'door-single',
    name: 'Single Door',
    category: 'Doors',
    style: 'Standard',
    width: 0.9,
    length: 0.1,
    height: 2.1,
    price: 8000,
    suitableFor: ['any'],
    color: '#78350f',
    finish: 'Solid wood panel door',
    image: '/images/furniture/doors/door-single.svg',
    mount: 'wall',
  },
  {
    id: 'door-double',
    name: 'Double Door',
    category: 'Doors',
    style: 'Classic',
    width: 1.8,
    length: 0.1,
    height: 2.1,
    price: 18000,
    suitableFor: ['living', 'dining'],
    color: '#78350f',
    finish: 'French doors with glass panels',
    image: '/images/furniture/doors/door-double.svg',
    mount: 'wall',
  },
  {
    id: 'door-sliding',
    name: 'Sliding Door',
    category: 'Doors',
    style: 'Modern',
    width: 2.4,
    length: 0.1,
    height: 2.2,
    price: 35000,
    suitableFor: ['living', 'bedroom'],
    color: '#374151',
    finish: 'Aluminum frame with glass',
    image: '/images/furniture/doors/door-sliding.svg',
    mount: 'wall',
  },
  {
    id: 'door-pocket',
    name: 'Pocket Door',
    category: 'Doors',
    style: 'Space-saving',
    width: 0.9,
    length: 0.1,
    height: 2.1,
    price: 15000,
    suitableFor: ['bathroom', 'bedroom', 'any'],
    color: '#f5f5f4',
    finish: 'Slides into wall cavity',
    image: '/images/furniture/doors/door-pocket.svg',
    mount: 'wall',
  },
  {
    id: 'window-standard',
    name: 'Standard Window',
    category: 'Doors',
    style: 'Classic',
    width: 1.2,
    length: 0.15,
    height: 1.2,
    price: 12000,
    suitableFor: ['any'],
    color: '#f5f5f4',
    finish: 'Double-glazed UPVC frame',
    image: '/images/furniture/windows/window-standard.svg',
    mount: 'wall',
  },
  {
    id: 'window-large',
    name: 'Large Picture Window',
    category: 'Doors',
    style: 'Modern',
    width: 2.4,
    length: 0.15,
    height: 1.5,
    price: 28000,
    suitableFor: ['living', 'bedroom'],
    color: '#374151',
    finish: 'Fixed glass with aluminum frame',
    image: '/images/furniture/windows/window-large.svg',
    mount: 'wall',
  },
  {
    id: 'window-floor',
    name: 'Floor-to-Ceiling Window',
    category: 'Doors',
    style: 'Contemporary',
    width: 1.5,
    length: 0.15,
    height: 2.4,
    price: 45000,
    suitableFor: ['living', 'bedroom'],
    color: '#1f2937',
    finish: 'Full-height glazing with slim frame',
    image: '/images/furniture/windows/window-floor.svg',
    mount: 'wall',
  },
  {
    id: 'window-bay',
    name: 'Bay Window',
    category: 'Doors',
    style: 'Traditional',
    width: 2.0,
    length: 0.6,
    height: 1.5,
    price: 55000,
    suitableFor: ['living', 'bedroom'],
    color: '#f5f5f4',
    finish: 'Three-panel projecting window',
    image: '/images/furniture/windows/window-bay.svg',
    mount: 'wall',
  },
  {
    id: 'window-skylight',
    name: 'Skylight',
    category: 'Doors',
    style: 'Modern',
    width: 1.0,
    length: 1.0,
    height: 0.15,
    price: 25000,
    suitableFor: ['bathroom', 'kitchen', 'any'],
    color: '#e5e7eb',
    finish: 'Roof-mounted with rain sensor',
    image: '/images/furniture/windows/window-skylight.svg',
    mount: 'ceiling',
  },
];

const ROOM_TEMPLATES: Record<RoomTemplateId, InteriorRoomTemplate> = {
  living: {
    name: 'Living Lounge',
    width: 18,
    length: 16,
    level: 0,
    description: 'Anchored living space with terrace connection and media wall.',
    tags: ['hosting', 'entertainment'],
    defaultMaterialId: 'earthy-lounge',
    defaultLightingId: 'golden-hour',
  },
  kitchen: {
    name: 'Chefs Kitchen',
    width: 14,
    length: 12,
    level: 0,
    description: 'Back-of-house prep with visual openness to dining.',
    tags: ['culinary', 'prep'],
    defaultMaterialId: 'artisan-kitchen',
    defaultLightingId: 'studio-daylight',
  },
  dining: {
    name: 'Dining Gallery',
    width: 12,
    length: 12,
    level: 0,
    description: 'Seating for 8 with direct connection to courtyard.',
    tags: ['hosting', 'dining'],
    defaultMaterialId: 'earthy-lounge',
    defaultLightingId: 'gallery-track',
  },
  bedroom: {
    name: 'Skyline Suite',
    width: 16,
    length: 15,
    level: 1,
    description: 'Primary suite with walk-in wardrobe and balcony edge.',
    tags: ['rest', 'luxe'],
    defaultMaterialId: 'nebula-suite',
    defaultLightingId: 'twilight',
  },
  bathroom: {
    name: 'Wellness Bath',
    width: 10,
    length: 9,
    level: 1,
    description: 'Double vanity, walk-in shower, and soaking tub niche.',
    tags: ['spa', 'ritual'],
    defaultMaterialId: 'spa-retreat',
    defaultLightingId: 'golden-hour',
  },
  study: {
    name: 'Creative Studio',
    width: 12,
    length: 10,
    level: 1,
    description: 'Flexible focus lounge with built-in library wall.',
    tags: ['work', 'creative'],
    defaultMaterialId: 'midnight-minimal',
    defaultLightingId: 'studio-daylight',
  },
};

const INSPIRATION_LIBRARY: MoodboardItem[] = [
  {
    id: 'inspo-terracotta',
    label: 'Terracotta Atrium',
    category: 'inspiration',
    swatch: '#c86b3c',
    note: 'Double-height atrium with diffused skylight and terracotta render.',
    sourceId: 'inspiration-terracotta',
  },
  {
    id: 'inspo-brutalist',
    label: 'Brutalist Calm',
    category: 'inspiration',
    swatch: '#4b5563',
    note: 'Board-formed concrete softened with linen drapery and foliage.',
    sourceId: 'inspiration-brutalist',
  },
  {
    id: 'inspo-himalayan',
    label: 'Himalayan Dawn',
    category: 'inspiration',
    swatch: '#f9a8d4',
    note: 'Rose quartz palette with woven wool textures and copper highlights.',
    sourceId: 'inspiration-himalayan',
  },
];

const DEFAULT_ROOMS: InteriorCatalog['defaultRooms'] = [
  { templateId: 'living', name: 'Great Room' },
  { templateId: 'kitchen', name: 'Show Kitchen' },
  { templateId: 'dining', name: 'Dining Nook' },
  { templateId: 'bedroom', name: 'Primary Suite' },
  { templateId: 'bathroom', name: 'Ensuite Bath' },
  { templateId: 'study', name: 'Creative Studio' },
];

const STATIC_INTERIOR_CATALOG: InteriorCatalog = {
  materials: MATERIAL_LIBRARY,
  lighting: LIGHTING_LIBRARY,
  furniture: FURNITURE_LIBRARY,
  templates: ROOM_TEMPLATES,
  inspiration: INSPIRATION_LIBRARY,
  defaultRooms: DEFAULT_ROOMS,
};

const deepClone = <T>(value: T): T => JSON.parse(JSON.stringify(value));

export const loadStaticInteriorCatalog = (): InteriorCatalog => deepClone(STATIC_INTERIOR_CATALOG);

export const fetchInteriorCatalog = async (): Promise<InteriorCatalog> => {
  await new Promise((resolve) => setTimeout(resolve, 350));
  return loadStaticInteriorCatalog();
};

export { STATIC_INTERIOR_CATALOG };

